# Generated by Django 4.2.5 on 2024-01-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.CharField(max_length=50, verbose_name="Изображение"),
        ),
    ]
